// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2025, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

public type ErrorInternalServerErrorInternalServerError record {|
    *http:InternalServerError;
    ErrorInternalServerError body;
|};

public type ErrorUserNotAvailable record {
    string status;
    string schemas?;
    string detail;
};

public type UserObjectListResponseObjectOk record {|
    *http:Ok;
    UserObjectListResponseObject body;
|};

public type ErrorInternalServerError record {
    string status;
    string schemas?;
    string detail;
};

public type ErrorUnauthorizedUnauthorized record {|
    *http:Unauthorized;
    ErrorUnauthorized body;
|};

public type ErrorSchemaNotFound record {
    string status;
    string schemas?;
    string detail;
};

public type ErrorGroupAlreadyAvailable record {
    string status;
    string schemas?;
    string detail;
};

public type ErrorInvalidInputBadRequest record {|
    *http:BadRequest;
    ErrorInvalidInput body;
|};

public type ErrorUnauthorized record {
    string schemas?;
    string detail?;
    string status;
};

public type ErrorUserNotAvailableNotFound record {|
    *http:NotFound;
    ErrorUserNotAvailable body;
|};

public type ErrorNoGroupAvailableNotFound record {|
    *http:NotFound;
    ErrorNoGroupAvailable body;
|};

public type ErrorGroupNotAvailableNotFound record {|
    *http:NotFound;
    ErrorGroupNotAvailable body;
|};

public type ErrorSchemaNotFoundNotFound record {|
    *http:NotFound;
    ErrorSchemaNotFound body;
|};

public type ErrorNoGroupAvailable record {
    string status;
    string[] schemas?;
    string detail;
};

public type GroupSearchResponseObjectOk record {|
    *http:Ok;
    GroupSearchResponseObject body;
|};

public type ErrorForbidden record {
    string schemas?;
    string detail?;
    string status;
};

public type ErrorInvalidInput record {
    string status;
    string schemas?;
    string scimType?;
    string detail;
};

public type ErrorGroupAlreadyAvailableConflict record {|
    *http:Conflict;
    ErrorGroupAlreadyAvailable body;
|};

public type ErrorGroupNotAvailable record {
    string status;
    string schemas?;
    string detail;
};

public type ErrorForbiddenForbidden record {|
    *http:Forbidden;
    ErrorForbidden body;
|};
