[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "scim"
version = "3.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = []
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-scim"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true